//! i143.e4.s15 (rafka-v2 #2842) acceptance 14: canonical product ids cross
//! the RDM / Rafka boundary unchanged. The fixture was generated by Rafka's
//! `rafka_iam_types::identity::encode_crockford_60bit` (its `generator`); RDM's
//! encoder, decoder and typed parsers must agree with every row, with no
//! remint or translation.

use rafka_mesh_entity::ids::{decode_crockford60, encode_crockford60};
use rafka_mesh_entity::{FabricId, MeshDigest, MeshId, NodeId};
use serde_json::Value;

fn rows() -> Vec<(u64, String)> {
    let v: Value = serde_json::from_str(include_str!("fixtures/crockford60-parity.json")).unwrap();
    assert_eq!(v["generator"], "rafka_iam_types::identity::encode_crockford_60bit");
    v["ids"].as_array().unwrap().iter().map(|r| (r["value"].as_u64().unwrap(), r["id"].as_str().unwrap().to_string())).collect()
}

#[test]
fn rdm_encodes_and_decodes_every_rafka_minted_id_identically() {
    let rows = rows();
    assert!(rows.len() >= 10);
    for (value, id) in rows {
        assert_eq!(encode_crockford60(value), id, "encode {value}");
        assert_eq!(decode_crockford60(&id), Some(value), "decode {id}");
    }
}

#[test]
fn every_rafka_minted_id_is_a_node_mesh_and_fabric_id_as_is() {
    for (_, id) in rows() {
        let quoted = format!("\"{id}\"");
        assert_eq!(NodeId::parse(&id).unwrap().as_str(), id);
        assert_eq!(MeshId::parse(&id).unwrap().as_str(), id);
        assert_eq!(FabricId::parse(&id).unwrap().as_str(), id);
        // Wire/serde: the same bare string in, the same bare string out.
        assert_eq!(serde_json::to_string(&serde_json::from_str::<NodeId>(&quoted).unwrap()).unwrap(), quoted);
        assert_eq!(serde_json::to_string(&serde_json::from_str::<MeshId>(&quoted).unwrap()).unwrap(), quoted);
        assert_eq!(serde_json::to_string(&serde_json::from_str::<FabricId>(&quoted).unwrap()).unwrap(), quoted);
    }
}

/// Acceptance 13: canonical ids survive the membership digest's encoding
/// exactly (the frame every gossip channel carries).
#[test]
fn a_membership_digest_carries_its_product_ids_exactly() {
    let (node_id, fabric_id) = (NodeId::mint(), FabricId::mint());
    let d = MeshDigest {
        fabric_id: fabric_id.clone(),
        node: rafka_mesh_entity::MeshNode {
            node_id: node_id.clone(),
            name: "mesh1.rpc.1".parse().unwrap(),
            endpoint_id: rafka_mesh_entity::EndpointId("key".into()),
            transport_addr: "127.0.0.1:41000".parse().unwrap(),
            incarnation: rafka_mesh_entity::IncarnationId::mint(),
            supersedes: None,
            runtime: None,
        },
        status: rafka_mesh_entity::MemberStatus::ReadyForTraffic,
        admin_api_base: None,
        emitted_at_rafka_ms: 1,
        digest_seq: 1,
        mesh_id: None,
        in_flight: None,
        extra: Default::default(),
        load: None,
        gossip: None,
        data_dir: None,
    };
    let back = MeshDigest::decode(&d.encode()).unwrap();
    assert_eq!(back, d);
    assert_eq!(back.node.node_id, node_id);
    assert_eq!(back.fabric_id, fabric_id);
    // A digest whose fabric id is not canonical does not decode.
    let mut raw: Value = serde_json::from_slice(&d.encode()).unwrap();
    raw["fabric_id"] = Value::String("fabric1".into());
    assert!(MeshDigest::decode(&serde_json::to_vec(&raw).unwrap()).is_none());
}
